ssh-server:
  port: 1022
  private-key:
    location: "conf/private.key"
  hash-replies:
    location: "conf/hash-replies.properties"
  regex-mapping:
    location: "conf/regex-mapping.properties"

spring:
  datasource:
    url: "jdbc:h2:file:./data/remote-ip-info-db"